# Generated by Django 6.0 on 2025-12-30 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(choices=[('BANK', 'Banco'), ('CASH', 'Efectivo'), ('WALLET', 'Billetera virtual'), ('CRYPTO', 'Cripto')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('USDT', 'Tether')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
